apiVersion: v1
kind: Pod
metadata:
  labels:
    run: {{.Chart.Name}}-{{.Chart.Version}}
  name: {{.Chart.Name}}
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    name: {{ .Values.image.name }}
    resources:
      limits:
        memory: {{ .Values.resources.limits.memory }}
        cpu: {{ .Values.resources.limits.cpu }} 
